1. Pandas DataFrame

A DataFrame is a table-like data structure in Python.

In [2]:
import pandas as pd

data = {
    "name": ["Dinesh", "Avinash", "Bala"],
    "department": ["AI", "HR", "AI"],
    "salary": [30000, 40000, 35000]
}

df = pd.DataFrame(data)

print(df)

      name department  salary
0   Dinesh         AI   30000
1  Avinash         HR   40000
2     Bala         AI   35000

In [3]:
df.head()
df.tail()
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        3 non-null      object
 1   department  3 non-null      object
 2   salary      3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

        salary
count      3.0
mean   35000.0
std     5000.0
min    30000.0
25%    32500.0
50%    35000.0
75%    37500.0
max    40000.0

2. groupby()

Used to group data and perform calculations.

Average salary by department

In [4]:
df.groupby("department")["salary"].mean()

department
AI    32500.0
HR    40000.0
Name: salary, dtype: float64

In [5]:
df.groupby("department")["salary"].agg(
    ["count", "mean", "sum", "max", "min"]
)

            count     mean    sum    max    min
department
AI              2  32500.0  65000  35000  30000
HR              1  40000.0  40000  40000  40000

3. merge()

merge() combines two DataFrames, similar to a SQL JOIN.

In [ ]:
employees = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Dinesh", "Arun", "Ravi"],
    "department_id": [10, 20, 10]
})

departments = pd.DataFrame({
    "department_id": [10, 20],
    "department_name": ["AI", "HR"]
})

result = pd.merge(
    employees,
    departments,
    on="department_id",
    how="inner"
)

print(result)

4. psycopg2

psycopg2 is a Python adapter used to connect Python applications directly to PostgreSQL.

In [7]:
pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 17.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="intern_db",
    user="postgres",
    password="your_password",
    port=5432
)

cursor = conn.cursor()

cursor.execute("SELECT * FROM employees")

rows = cursor.fetchall()

for row in rows:
    print(row)

cursor.close()
conn.close()